# Feature Scaling

## Techniques : 
   ### 1)Robust Scaling
   ### 2)Scaling to vector unit length (Scaling to unit norm)

## Robust Scaling- Boston Dataset

In [2]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from sklearn.datasets import load_boston
bos=load_boston()

In [5]:
bos

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [6]:
bosds=pd.DataFrame(bos.data,columns=bos.feature_names)
bosds['MEDV']=bos.target
bosds.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [7]:
## TT split

In [11]:
X=bosds.iloc[:,:-1]
y=bosds['MEDV']

In [12]:
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [13]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [15]:
## Robust Scaling

In [18]:
from sklearn.preprocessing import RobustScaler
rs=RobustScaler()
rs.fit(X_train)  ## fit the scalar to train ,it will learn the parameters

RobustScaler()

In [20]:
## scaler stores the median values of the features as learned from train set
rs.center_

array([2.62660e-01, 0.00000e+00, 8.56000e+00, 0.00000e+00, 5.38000e-01,
       6.21550e+00, 7.94500e+01, 3.21570e+00, 5.00000e+00, 3.11000e+02,
       1.91000e+01, 3.91605e+02, 1.11600e+01])

In [21]:
## scaler stores the median values of the features as learned from train set
rs.scale_

array([3.030275e+00, 2.000000e+01, 1.315000e+01, 1.000000e+00,
       1.792500e-01, 7.520000e-01, 4.857500e+01, 2.971650e+00,
       2.000000e+01, 3.900000e+02, 2.800000e+00, 1.963250e+01,
       9.982500e+00])

In [22]:
## transform the train and test

X_train_scaled=rs.transform(X_train)
X_test_scaled=rs.transform(X_test)

In [23]:
X_train_scaled=pd.DataFrame(X_train_scaled,columns=X_train.columns)
X_test_scaled=pd.DataFrame(X_test_scaled,columns=X_test.columns)

In [27]:
## median of original ds
## np.round to reduce the no of decimals to 1
np.round(X_train.median(),1)

CRIM         0.3
ZN           0.0
INDUS        8.6
CHAS         0.0
NOX          0.5
RM           6.2
AGE         79.4
DIS          3.2
RAD          5.0
TAX        311.0
PTRATIO     19.1
B          391.6
LSTAT       11.2
dtype: float64

In [26]:
np.round(X_train_scaled.median(),1)

CRIM      -0.0
ZN         0.0
INDUS      0.0
CHAS       0.0
NOX        0.0
RM        -0.0
AGE        0.0
DIS        0.0
RAD        0.0
TAX        0.0
PTRATIO    0.0
B         -0.0
LSTAT      0.0
dtype: float64

## Scaling to vector unit length (Scaling to unit norm)

In [38]:
from sklearn.preprocessing import Normalizer

In [39]:
## Scaling to L1

In [45]:
sc=Normalizer(norm='l1')
sc.fit(X_train)
X_train_scale=sc.transform(X_train)
X_test_scale=sc.transform(X_test)

In [46]:
## calculate the manhattan distance observation per observation

np.round(np.linalg.norm(X_train_scale,ord=1,axis=1),1)

array([1024.1,  744. , 1003.5,  858. ,  732.4,  859.3,  845.9,  847. ,
        888.1,  826.7,  705.9,  808.9,  734. ,  784.6,  785.1,  819.6,
       1212.9, 1258. ,  757.6, 1223. , 1236.1,  890.2, 1166.8, 1270. ,
        919. ,  925.9, 1197. ,  770.3, 1118. ,  886.7,  719. ,  952. ,
        933.4,  745. ,  805.6,  825.1,  678.5,  947.7,  910. ,  816. ,
        769.1,  832.4,  763.5,  777. ,  850.4, 1137.7,  802.1,  703.4,
        802.6,  688. ,  801.8,  877.3,  753.8,  912.4,  936.7,  813.6,
       1194. ,  771.9,  739.5,  825.9,  890.8,  891.6,  844.4,  927.1,
        998.6,  903.3, 1250.3,  739.5, 1095.3,  857.7,  834.8,  738.4,
        855.1, 1238.4,  828.6,  958.4,  775. ,  923.4,  859.6,  830.7,
        782.3,  796.8,  953.2,  857.9, 1249.9,  716.7,  803.9,  978.8,
       1186.9,  904. , 1238.2,  981.6,  884.9,  924.9,  694.1,  725.2,
        832.4,  717.7,  917. , 1263.9,  836.7,  813.5,  992.5,  823.4,
       1224.3,  712.1,  841.2,  950.3,  702.6,  791.9,  830.4,  742.1,
      

In [47]:
## scaled data

np.round(np.linalg.norm(X_train_scale,ord=1,axis=1),1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [48]:
## now each feature vector has l1 norm of 1

In [49]:
X_train_scale=pd.DataFrame(X_train_scale,columns=X_train.columns)
X_test_scale=pd.DataFrame(X_test_scale,columns=X_test.columns)

In [50]:
X_train.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  354.000000  354.000000  354.000000  354.000000  354.000000  354.000000   
mean     3.358284   11.809322   11.078757    0.064972    0.556098    6.308427   
std      8.353223   23.653056    6.993821    0.246825    0.115601    0.702009   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.073425    0.000000    4.950000    0.000000    0.450000    5.895250   
50%      0.262660    0.000000    8.560000    0.000000    0.538000    6.215500   
75%      3.103700   20.000000   18.100000    0.000000    0.629250    6.647250   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  354.000000  354.000000  354.000000  354.000000  354.000000  354.000000   
mean    68.994068    3.762459    9.353107  401.782486   18.473446  360.601186   
std     28.038429    2.067661    8.671999  170.592404    2.224809   85.621945   
min      2.900000    1.174200    1.000000  187.000000   12.600000    0.320000   
25%     45.175000    2.107650    4.000000  276.000000   17.400000  376.057500   
50%     79.450000    3.215700    5.000000  311.000000   19.100000  391.605000   
75%     93.750000    5.079300   24.000000  666.000000   20.200000  395.690000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  354.000000  
mean    12.440650  
std      7.078485  
min      1.730000  
25%      6.735000  
50%     11.160000  
75%     16.717500  
max     36.980000

In [51]:
X_train_scale.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  354.000000  354.000000  354.000000  354.000000  354.000000  354.000000   
mean     0.003022    0.014491    0.011731    0.000073    0.000620    0.007221   
std      0.007018    0.028764    0.006854    0.000283    0.000115    0.001620   
min      0.000008    0.000000    0.000577    0.000000    0.000424    0.002996   
25%      0.000093    0.000000    0.006243    0.000000    0.000545    0.006061   
50%      0.000311    0.000000    0.010421    0.000000    0.000611    0.007376   
75%      0.002983    0.024709    0.015120    0.000000    0.000657    0.008358   
max      0.066782    0.121905    0.035787    0.001422    0.001337    0.011541   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  354.000000  354.000000  354.000000  354.000000  354.000000  354.000000   
mean     0.075687    0.004479    0.009336    0.427642    0.020880    0.411273   
std      0.029466    0.002780    0.007262    0.114922    0.003751    0.124328   
min      0.004348    0.000919    0.001163    0.250885    0.014363    0.000374   
25%      0.055411    0.002206    0.004740    0.346035    0.016876    0.318534   
50%      0.078917    0.003923    0.006021    0.393483    0.021129    0.456271   
75%      0.098186    0.006456    0.018223    0.526258    0.024014    0.498519   
max      0.144310    0.016269    0.028684    0.795970    0.030523    0.578661   

            LSTAT  
count  354.000000  
mean     0.013544  
std      0.007204  
min      0.001879  
25%      0.008473  
50%      0.012262  
75%      0.017204  
max      0.041723

In [52]:
## Scaling to l2

In [65]:
sca=Normalizer(norm='l2')
sca.fit(X_train)
X_train_scale=sca.transform(X_train)
X_test_scale=sca.transform(X_test)

In [66]:
## calculate the euclidean distance observation per observation

np.round(np.linalg.norm(X_train,ord=2,axis=1),1)

array([600.5, 458.4, 598. , 519.1, 434. , 511. , 527.9, 496.7, 675.2,
       496.5, 450.2, 492.1, 453.5, 492.4, 492.9, 491.5, 770.1, 782.2,
       465.2, 759.8, 778.6, 535.3, 764.4, 781.5, 561.9, 562.8, 768.1,
       468.2, 725.5, 673.1, 458.8, 572.5, 559.8, 488. , 490.2, 488.9,
       441.3, 680.4, 675.6, 483.9, 483.9, 506.2, 474.8, 481.9, 517.8,
       747.8, 503.3, 438.2, 483. , 424. , 478.8, 519.9, 451.4, 546.2,
       558.3, 516.9, 773.8, 470.4, 467.5, 501.6, 674.5, 528.1, 508.2,
       677.1, 593.2, 556.5, 781.9, 465.9, 707.6, 509.6, 501.3, 449.4,
       512.5, 778.8, 483.6, 587.7, 485.4, 558.1, 673.1, 504.6, 494.9,
       509. , 589.2, 510.6, 777. , 439.2, 478.8, 593.3, 760. , 534.5,
       779.9, 586.6, 551.3, 558.4, 446.2, 418.8, 496. , 407.8, 676.2,
       782.8, 671. , 499. , 593.6, 482.6, 779.2, 456.1, 483.4, 573.4,
       456.5, 477.3, 493.3, 485.7, 490.5, 716.1, 497.2, 760.6, 524.9,
       672.1, 488.2, 443.7, 751. , 492.5, 424.3, 458.7, 783. , 596.4,
       482.9, 557.2,

In [67]:
np.round(np.linalg.norm(X_train_scale,ord=2,axis=1),1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [68]:
X_train.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  354.000000  354.000000  354.000000  354.000000  354.000000  354.000000   
mean     3.358284   11.809322   11.078757    0.064972    0.556098    6.308427   
std      8.353223   23.653056    6.993821    0.246825    0.115601    0.702009   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.073425    0.000000    4.950000    0.000000    0.450000    5.895250   
50%      0.262660    0.000000    8.560000    0.000000    0.538000    6.215500   
75%      3.103700   20.000000   18.100000    0.000000    0.629250    6.647250   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  354.000000  354.000000  354.000000  354.000000  354.000000  354.000000   
mean    68.994068    3.762459    9.353107  401.782486   18.473446  360.601186   
std     28.038429    2.067661    8.671999  170.592404    2.224809   85.621945   
min      2.900000    1.174200    1.000000  187.000000   12.600000    0.320000   
25%     45.175000    2.107650    4.000000  276.000000   17.400000  376.057500   
50%     79.450000    3.215700    5.000000  311.000000   19.100000  391.605000   
75%     93.750000    5.079300   24.000000  666.000000   20.200000  395.690000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  354.000000  
mean    12.440650  
std      7.078485  
min      1.730000  
25%      6.735000  
50%     11.160000  
75%     16.717500  
max     36.980000