# Feature Scaling

## Techniques Used : Normalization (or min-max normalization), Standardization (or z-score normalization),Robust Scaling (Scaling to median and quantiles)
###  Normalization =X-X(min)/X(max)-X(min)
### Standardization=X-X(mean)/X(sd)
### Robust scaling=(X - X(median)) / IQR     ------ (X-X(median)/(75th quantile(X)-25th quantile(X))

## Lending Club Loan Data -Kaggle

In [3]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
loan=pd.read_csv('D:/ShakthiSai -Keerthana BABI and Learnings/AI and Machine Learning/Feature Engineering/loan.csv')

C:\Users\Vikee\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (19,47,55,112,123,124,125,128,129,130,133,139,140,141) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [6]:
loan.head()

id  member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0 NaN        NaN       2500         2500           2500.0   36 months   
1 NaN        NaN      30000        30000          30000.0   60 months   
2 NaN        NaN       5000         5000           5000.0   36 months   
3 NaN        NaN       4000         4000           4000.0   36 months   
4 NaN        NaN      30000        30000          30000.0   60 months   

   int_rate  installment grade sub_grade  ... hardship_payoff_balance_amount  \
0     13.56        84.92     C        C1  ...                            NaN   
1     18.94       777.23     D        D2  ...                            NaN   
2     17.97       180.69     D        D1  ...                            NaN   
3     18.94       146.51     D        D2  ...                            NaN   
4     16.14       731.78     C        C4  ...                            NaN   

  hardship_last_payment_amount disbursement_method  debt_settlement_flag  \
0                          NaN                Cash                     N   
1                          NaN                Cash                     N   
2                          NaN                Cash                     N   
3                          NaN                Cash                     N   
4                          NaN                Cash                     N   

  debt_settlement_flag_date settlement_status settlement_date  \
0                       NaN               NaN             NaN   
1                       NaN               NaN             NaN   
2                       NaN               NaN             NaN   
3                       NaN               NaN             NaN   
4                       NaN               NaN             NaN   

  settlement_amount  settlement_percentage settlement_term  
0               NaN                    NaN             NaN  
1               NaN                    NaN             NaN  
2               NaN                    NaN             NaN  
3               NaN                    NaN             NaN  
4               NaN                    NaN             NaN  

[5 rows x 145 columns]

In [ ]:
## Let’s import three columns — Loan amount, int_rate and installment
## and the first 1000 rows in the data set (to reduce the computation time)

In [9]:
cols = ['loan_amnt', 'int_rate', 'installment']
data = pd.read_csv('D:/ShakthiSai -Keerthana BABI and Learnings/AI and Machine Learning/Feature Engineering/loan.csv', nrows = 1000, usecols = cols)

In [10]:
data.head()

loan_amnt  int_rate  installment
0       2500     13.56        84.92
1      30000     18.94       777.23
2       5000     17.97       180.69
3       4000     18.94       146.51
4      30000     16.14       731.78

In [11]:
data.describe()

loan_amnt     int_rate  installment
count   1000.000000  1000.000000  1000.000000
mean   15657.750000    13.050820   454.249320
std    10276.000797     4.913656   287.383903
min     1000.000000     6.460000    30.640000
25%     7500.000000     8.810000   235.800000
50%    13000.000000    11.800000   377.090000
75%    22000.000000    16.140000   621.277500
max    40000.000000    30.750000  1379.960000

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   loan_amnt    1000 non-null   int64  
 1   int_rate     1000 non-null   float64
 2   installment  1000 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 23.6 KB


## Normalization

In [19]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
scaled_features=mms.fit_transform(data)

In [20]:
data.head()


loan_amnt  int_rate  installment
0       2500     13.56        84.92
1      30000     18.94       777.23
2       5000     17.97       180.69
3       4000     18.94       146.51
4      30000     16.14       731.78

In [22]:
scaled_features

array([[0.03846154, 0.29230136, 0.04022767],
       [0.74358974, 0.51379168, 0.55330833],
       [0.1025641 , 0.47385755, 0.11120416],
       ...,
       [0.48717949, 0.15932483, 0.45786767],
       [0.12820513, 0.55413751, 0.14236801],
       [0.71794872, 0.32976534, 0.71676845]])

In [25]:
scaled_dataset=pd.DataFrame(data=scaled_features,columns=["loan_amt","int_rate","installment"])
scaled_dataset.head()

loan_amt  int_rate  installment
0  0.038462  0.292301     0.040228
1  0.743590  0.513792     0.553308
2  0.102564  0.473858     0.111204
3  0.076923  0.513792     0.085873
4  0.743590  0.398518     0.519625

## Now let’s check the mean and standard deviation values

In [39]:
print(scaled_dataset.mean(axis=0))

loan_amt       0.375840
int_rate       0.271339
installment    0.313943
dtype: float64


In [40]:
print(scaled_dataset.std(axis=0))

loan_amt       0.263487
int_rate       0.202291
installment    0.212984
dtype: float64


### After MinMaxScaling, the distributions are not centered at zero and the standard deviation is not 1.

## Standardization

In [28]:
from sklearn.preprocessing import StandardScaler

In [30]:
ss=StandardScaler()
sscaled_features=ss.fit_transform(data)
sscaled_features

array([[-1.28107559,  0.10367734, -1.28578574],
       [ 1.39640185,  1.199133  ,  1.12442725],
       [-1.03766855,  1.0016252 , -0.95237137],
       ...,
       [ 0.42277369, -0.55400328,  0.67609164],
       [-0.94030574,  1.39867697, -0.8059782 ],
       [ 1.29903903,  0.28896817,  1.89228641]])

In [31]:
sscaled_dataset=pd.DataFrame(data=sscaled_features,columns=["loan_amt","int_rate","installment"])
sscaled_dataset.head()

loan_amt  int_rate  installment
0 -1.281076  0.103677    -1.285786
1  1.396402  1.199133     1.124427
2 -1.037669  1.001625    -0.952371
3 -1.135031  1.199133    -1.071366
4  1.396402  0.629007     0.966197

### Now let’s check the mean and standard deviation values

In [34]:
print(sscaled_dataset.mean(axis=0))

loan_amt       4.041212e-17
int_rate      -3.208545e-16
installment   -9.348078e-17
dtype: float64


In [37]:
print(sscaled_dataset.std(axis=0))

loan_amt       1.0005
int_rate       1.0005
installment    1.0005
dtype: float64


### As expected, the mean of each variable is now around zero and the standard deviation is set to 1. 
### Thus, all the variable values lie within the same range.

## Robust Scaling-Scaling to median and quantiles

### Scaling using median and quantiles consists of subtracting the median to all the observations and then dividing by the interquartile difference. It Scales features using statistics that are robust

In [42]:
from sklearn.preprocessing import RobustScaler

In [43]:
rs=RobustScaler()
rscaled_features=rs.fit_transform(data)
rscaled_features

array([[-0.72413793,  0.24010914, -0.75794307],
       [ 1.17241379,  0.97407913,  1.03803724],
       [-0.55172414,  0.84174625, -0.50949796],
       ...,
       [ 0.48275862, -0.2005457 ,  0.70395808],
       [-0.48275862,  1.10777626, -0.40041248],
       [ 1.10344828,  0.36425648,  1.61021071]])

In [44]:
rscaled_dataset=pd.DataFrame(data=rscaled_features,columns=["loan_amt","int_rate","installment"])
rscaled_dataset.head()

loan_amt  int_rate  installment
0 -0.724138  0.240109    -0.757943
1  1.172414  0.974079     1.038037
2 -0.551724  0.841746    -0.509498
3 -0.620690  0.974079    -0.598167
4  1.172414  0.592087     0.920132

### Now let’s check the mean and standard deviation values

In [45]:
print(rscaled_dataset.mean(axis=0))

loan_amt       0.183293
int_rate       0.170644
installment    0.200166
dtype: float64


In [46]:
print(rscaled_dataset.std(axis=0))

loan_amt       0.708690
int_rate       0.670349
installment    0.745527
dtype: float64


### As you can see, the distributions are not centered in zero and the standard deviation is not 1.

In [48]:
print(rscaled_dataset.median(axis=0))

loan_amt       0.0
int_rate       0.0
installment    0.0
dtype: float64


## Medians are centered at 0